FROM python:3.6.0

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        postgresql-client \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app

ARG requirements
COPY requirements/ requirements/
RUN pip install -r requirements/$requirements

# CELERY
# create unprivileged user
RUN adduser --disabled-password --gecos '' celery

EXPOSE 8000
